apiVersion: v1
kind: Service
metadata:
  name: messenger
  namespace: messenger
spec:
  type: NodePort
  # Метки селектора, использованные в шаблоне подов при создании объекта Deployment.
  selector:
    app: auth
    version: blue
  ports:
    - name: http
      protocol: TCP
      port: 8080 
      targetPort: 8080 
      nodePort: 30001 
